--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.09.2025 23:16:28
-- Server version: 8.0.42
--

SET NAMES 'utf8';

INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(1, 'Повар', 'Среднее профессиональное', 1, 'Приготовление блюд согласно меню');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(2, 'Су-шеф', 'Среднее профессиональное', 1, 'Помощь главному повару, контроль кухни');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(3, 'Официант', 'Среднее', 0, 'Обслуживание гостей за столами');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(4, 'Бармен', 'Среднее', 0, 'Приготовление напитков, работа с барной стойкой');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(5, 'Менеджер ресторана', 'Высшее', 0, 'Общее управление рестораном');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(6, 'Хостес', 'Среднее', 0, 'Приветствие и рассадка гостей');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(7, 'Уборщик', NULL, 0, 'Уборка помещений ресторана');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(8, 'Сомелье', 'Высшее', 0, 'Подбор и подача вин');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(9, 'Кондитер', 'Среднее профессиональное', 1, 'Приготовление десертов и выпечки');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(10, 'Кассир', 'Среднее', 0, 'Приём оплаты и работа с кассовым аппаратом');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(11, 'Пекарь', 'Среднее профессиональное', 1, 'Выпечка хлебобулочных изделий');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(12, 'Посудомойка', NULL, 0, 'Мытьё посуды и кухонного инвентаря');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(13, 'Шеф-повар', 'Высшее', 1, 'Руководство кухней, разработка меню');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(14, 'Бариста', 'Среднее', 0, 'Приготовление кофе и кофейных напитков');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(15, 'Охранник', 'Среднее', 1, 'Обеспечение безопасности ресторана');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(16, 'Мойщик полов', NULL, 0, 'Уборка пола и помещений');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(17, 'Летний официант', 'Среднее', 0, 'Временное обслуживание гостей летом');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(18, 'Повар горячего цеха', 'Среднее профессиональное', 1, 'Приготовление горячих блюд');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(19, 'Повар холодного цеха', 'Среднее профессиональное', 1, 'Приготовление салатов и закусок');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(20, 'Стажёр повара', 'Среднее профессиональное', 0, 'Помощь повару, обучение');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(21, 'Менеджер по закупкам', 'Высшее', 0, 'Закупка продуктов и материалов');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(22, 'Доставка', 'Среднее', 1, 'Доставка заказов клиентам');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(23, 'Администратор', 'Высшее', 0, 'Контроль работы персонала, встречи гостей');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(24, 'Старший официант', 'Среднее', 0, 'Контроль работы официантов');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(25, 'Помощник бармена', 'Среднее', 0, 'Помощь бармену, подготовка ингредиентов');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(26, 'Кулинарный инспектор', 'Высшее', 1, 'Контроль качества блюд и санитарии');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(27, 'Повар-сушист', 'Среднее профессиональное', 1, 'Приготовление суши и роллов');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(28, 'Курьер', 'Среднее', 1, 'Доставка заказов клиентам');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(29, 'Массовик-затейник', 'Среднее', 0, 'Организация мероприятий и праздников');
INSERT INTO restaurants.positions(id, name_position, education, position_dangerous, describe_position) VALUES
(30, 'Ведущий мероприятий', 'Высшее', 0, 'Проведение банкетов и событий');