--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.09.2025 23:16:28
-- Server version: 8.0.42
--

SET NAMES 'utf8';

INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(1, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(2, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '10:00:00', 5, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(3, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '09:00:00', 6, '09:00:00', 4);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(4, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, '10:00:00', 5);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(5, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '11:00:00', 4, '11:00:00', 4);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(6, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(7, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '12:00:00', 3, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(8, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '10:00:00', 5, '12:00:00', 3);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, '10:00:00', 6);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(10, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '09:00:00', 6, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(11, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 8, '08:00:00', 8);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(12, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(13, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '09:00:00', 5, '09:00:00', 4);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(14, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '10:00:00', 6, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(15, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, '11:00:00', 5);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(16, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 8, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(17, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '09:00:00', 5, '10:00:00', 4);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(18, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(19, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '12:00:00', 3, '12:00:00', 3);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(20, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '10:00:00', 5, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(21, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, '10:00:00', 5);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(22, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 8, '08:00:00', 8);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(23, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(24, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '09:00:00', 5, '10:00:00', 4);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(25, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '10:00:00', 5, NULL, NULL);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(26, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, '09:00:00', 5);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(27, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 8, '08:00:00', 8);
INSERT INTO restaurants.time_table(id, monday_time, monday_cout_hour, tuesday_time, tuesday_cout_hour, wednesday_time, wednesday_cout_hour, thursday_time, thursday_cout_hour, friday_time, friday_cout_hour, saturday_time, saturday_cout_hour, sunday_time, sunday_cout_hour) VALUES
(28, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, '08:00:00', 9, NULL, NULL, NULL, NULL);