--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27.09.2025 23:16:28
-- Server version: 8.0.42
--

SET NAMES 'utf8';
